# Generated by Django 5.1.7 on 2025-03-19 08:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='bookstore',
            field=models.ManyToManyField(to='books.bookstore'),
        ),
        migrations.AddField(
            model_name='book',
            name='sold',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='book',
            name='stock',
            field=models.IntegerField(default=0),
        ),
    ]
