# Generated by Django 5.1.7 on 2025-04-04 09:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0002_book_bookstore_book_sold_book_stock'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='book',
            name='sold',
        ),
        migrations.RemoveField(
            model_name='book',
            name='stock',
        ),
        migrations.CreateModel(
            name='BookstoreStock',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('stock', models.IntegerField(default=0)),
                ('sold', models.IntegerField(default=0)),
                ('book', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='books.book')),
                ('bookstore', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='books.bookstore')),
            ],
            options={
                'unique_together': {('book', 'bookstore')},
            },
        ),
    ]
